/* DEFINITIONS DES COMMANDES CLIENT ET REPONSES DU SERVEUR ROBOA
 *
 * (d)2005 David.Romeuf@univ-lyon1.fr
*/

#ifndef _CMDREP_ROBOA

#define _CMDREP_ROBOA

#include <qstring.h>

/* Liste des commandes du client au serveur ROBOA
*/
#define NB_CMD_CLIENT_ROBOA				16	// On compte aussi la derniere chaine vide

#define ROBOA_CMD_SESAMEOUVRETOI		0
#define ROBOA_CMD_EN_ATTENTE			1
#define ROBOA_CMD_ARRET					2
#define ROBOA_CMD_DECONNEXION			3
#define ROBOA_CMD_INITCONFIGHW			4
#define ROBOA_CMD_RECH_INDEX_AXE		5
#define ROBOA_CMD_RECH_POSREPOS_AXE		6
#define ROBOA_CMD_POSAXESPASENC			7
#define ROBOA_CMD_POSAXESPASMOT			8
#define ROBOA_CMD_MVTAXEPASMOT			9
#define ROBOA_CMD_DEMARRERAXE			10
#define ROBOA_CMD_DEMARRERTOUSAXES		11
#define ROBOA_CMD_ARRETAXE				12
#define ROBOA_CMD_ARRETTOUSAXES			13
#define ROBOA_CMD_ARRETTOUSAXESURGENT	14

static QString ListeCmdClientROBOA[NB_CMD_CLIENT_ROBOA]=
{
	"azop?e&ikk#iekl_&&ieorpnbedj1az2#[o](6xczalke-4&2a3z1e7r5d9",
	"<EN-ATTENTE?>",
	"<ARRET-SERVEUR-ROBOA>",
	"<DECONNEXION>",
	"<INIT-CONFIG-PCI7334-MID7604>",
	"<RECHERCHER-INDEX-AXE>",
	"<RECHERCHER-POSREPOS-AXE>",
	"<POSITIONS-AXES-PASENC?>",
	"<POSITIONS-AXES-PASMOT?>",
	"<MVT-AXE-PASMOT>",
	"<DEMARRER-AXE>",
	"<DEMARRER-AXES>",
	"<ARRET-AXE>",
	"<ARRET-AXES>",
	"<ARRET-AXES-URGENT>",
	""
};

/* Liste des reponses du serveur ROBOA au client
*/
#define NB_REP_SERVEUR_ROBOA				25	// On compte aussi la derniere chaine vide

#define ROBOA_REP_CMD_INCONNUE				0
#define ROBOA_REP_EN_ATTENTE				1
#define ROBOA_REP_OKINIT					2
#define ROBOA_REP_NONINIT					3
#define ROBOA_REP_OKINDEXAXE				4
#define ROBOA_REP_NONOKINDEXAXE				5
#define ROBOA_REP_POSAXESPASENC				6
#define ROBOA_REP_POSAXESPASMOT				7
#define ROBOA_REP_NONPOSAXESPASENC			8
#define ROBOA_REP_NONPOSAXESPASMOT			9
#define ROBOA_REP_OKMVTAXEPASMOT			10
#define ROBOA_REP_NONOKMVTAXEPASMOT			11
#define ROBOA_REP_OKDEMARRERAXE				12
#define ROBOA_REP_NONOKDEMARRERAXE			13
#define ROBOA_REP_OKDEMARRERAXES			14
#define ROBOA_REP_NONOKDEMARRERAXES			15
#define ROBOA_REP_OKARRETAXE				16
#define ROBOA_REP_NONOKARRETAXE				17
#define ROBOA_REP_OKARRETAXES				18
#define ROBOA_REP_NONOKARRETAXES			19
#define ROBOA_REP_OKARRETAXESURGENT			20
#define ROBOA_REP_NONOKARRETAXESURGENT		21
#define ROBOA_REP_OKPOSREPOSAXE				22
#define ROBOA_REP_NONOKPOSREPOSAXE			23

static QString ListeRepServeurROBOA[NB_REP_SERVEUR_ROBOA]=
{
	"[<?>]",
	"[<ROBOA-EN-ATTENTE>]",
	"[<INIT-CONFIG-PCI7334-MID7604-OK>]",
	"[<INIT-CONFIG-PCI7334-MID7604-NONOK>]",
	"[<RECHERCHER-INDEX-AXE-OK>]",
	"[<RECHERCHER-INDEX-AXE-NONOK>]",
	"[<POSITIONS-AXES-PASENC>]",
	"[<POSITIONS-AXES-PASMOT>]",
	"[<POSITIONS-AXES-PASENC>] ? ? ? ?",
	"[<POSITIONS-AXES-PASMOT>] ? ? ? ?",
	"[<MVT-AXE-PASMOT-OK>]",
	"[<MVT-AXE-PASMOT-NONOK>]",
	"[<DEMARRER-AXE-OK>]",
	"[<DEMARRER-AXE-NONOK>]",
	"[<DEMARRER-AXES-OK>]",
	"[<DEMARRER-AXES-NONOK>]",
	"[<ARRET-AXE-OK>]",
	"[<ARRET-AXE-NONOK>]",
	"[<ARRET-AXES-OK>]",
	"[<ARRET-AXES-NONOK>]",
	"[<ARRET-AXES-URGENT-OK>]",
	"[<ARRET-AXES-URGENT-NONOK>]",
	"[<RECHERCHER-POSREPOS-AXE-OK>]",
	"[<RECHERCHER-POSREPOS-AXE-NONOK>]",
	""
};

#endif

