// DEFINITIONS DES COMMANDES CLIENT ET REPONSES DU SERVEUR CAMEROA
//
// (d)2006 David.Romeuf@univ-lyon1.fr
//

#ifndef _CMDREP_CAMEROA

#define _CMDREP_CAMEROA

#include <qstring.h>

// Liste des commandes du client au serveur CAMEROA
//
#define NB_CMD_CLIENT_CAMEROA		27	// On compte aussi la derniere chaine vide

#define CAMEROA_CMD_SESAMEOUVRETOI	0
#define CAMEROA_CMD_EN_ATTENTE		1
#define CAMEROA_CMD_ARRET			2
#define CAMEROA_CMD_DECONNEXION		3
#define CAMEROA_CMD_CTEMP			4
#define CAMEROA_CMD_CTPI			5
#define CAMEROA_CMD_CTPC			6
#define CAMEROA_CMD_POSEI			7
#define CAMEROA_CMD_ARRETPOSE		8
#define CAMEROA_CMD_FSHUTTEROPEN	9
#define CAMEROA_CMD_FSHUTTERCLOSE	10
#define CAMEROA_CMD_FANLOW			11
#define CAMEROA_CMD_FANMEDIUM		12
#define CAMEROA_CMD_FANHIGH			13
#define CAMEROA_CMD_FANOFF			14
#define CAMEROA_CMD_TEMPCCD			15
#define CAMEROA_CMD_TEMPRADIATEUR	16
#define CAMEROA_CMD_PUIPELTIER		17
#define CAMEROA_CMD_MODEPOSECAOBTU	18
#define CAMEROA_CMD_MODEPOSECSOBTU	19
#define CAMEROA_CMD_POSEDOUBLEI		20
#define CAMEROA_CMD_POSEIBIAS		21
#define CAMEROA_CMD_POSEIDARK		22
#define CAMEROA_CMD_CTPD			23
#define CAMEROA_CMD_PARAMAMPLIPROFH	24
#define CAMEROA_CMD_PARAMAMPLIPROFV	25

static QString ListeCmdClientCamerOA[NB_CMD_CLIENT_CAMEROA]=
{
	"dsbh23%HDdoeo6762dszvfs%cxhzizn8-ern6(djk,cds.?udeeiz5",
	"<EN-ATTENTE?>",
	"<ARRET-SERVEUR-CAMEROA>",
	"<DECONNEXION>",
	"<CONS-TEMP>",
	"<CONS-TPI>",
	"<CONS-TPC>",
	"<POSE-IMAGE>",
	"<STOP-POSE-IMAGE>",
	"<OBTU-OUVERT>",
	"<OBTU-FERME>",
	"<VENT-LOW>",
	"<VENT-MEDIUM>",
	"<VENT-HIGH>",
	"<VENT-OFF>",
	"<TEMP-CCD>",
	"<TEMP-RADIATEUR>",
	"<PUI-PELTIER>",
	"<MODE-POSEC-A-OBTU>",
	"<MODE-POSEC-S-OBTU>",
	"<POSE-IMAGE-DOUBLE>",
	"<POSE-IMAGE-BIAS>",
	"<POSE-IMAGE-DARK>",
	"<CONS-TPD>",
	"<PARAM-AMPLI-PROFIL-H>",
	"<PARAM-AMPLI-PROFIL-V>",
	""
};

// Liste des reponses du serveur CAMEROA au client
//
#define NB_REP_SERVEUR_CAMEROA				31	// On compte aussi la derniere chaine vide

#define CAMEROA_REP_CMD_INCONNUE			0
#define CAMEROA_REP_EN_ATTENTE				1
#define CAMEROA_REP_OK_CTEMP				2
#define CAMEROA_REP_NONOK_CTEMP				3
#define CAMEROA_REP_OK_CTPI					4
#define CAMEROA_REP_NONOK_CTPI				5
#define CAMEROA_REP_OK_CTPC					6
#define CAMEROA_REP_NONOK_CTPC				7
#define CAMEROA_REP_OK_POSEI				8
#define CAMEROA_REP_OK_ARRETPOSE			9
#define CAMEROA_REP_OK_FSHUTTEROPEN			10
#define CAMEROA_REP_OK_FSHUTTERCLOSE		11
#define CAMEROA_REP_OK_FANLOW				12
#define CAMEROA_REP_OK_FANMEDIUM			13
#define CAMEROA_REP_OK_FANHIGH				14
#define CAMEROA_REP_OK_FANOFF				15
#define CAMEROA_REP_TEMPCCD					16
#define CAMEROA_REP_TEMPRADIATEUR			17
#define CAMEROA_REP_PUIPELTIER				18
#define CAMEROA_REP_OK_MODEPOSECAOBTU		19
#define CAMEROA_REP_OK_MODEPOSECSOBTU		20
#define CAMEROA_REP_OK_POSEDOUBLEI			21
#define CAMEROA_REP_OK_POSEIBIAS			22
#define CAMEROA_REP_OK_POSEIDARK			23
#define CAMEROA_REP_OK_CTPD					24
#define CAMEROA_REP_NONOK_CTPD				25
#define CAMEROA_REP_OK_PARAMAMPLIPROFH		26
#define CAMEROA_REP_NONOK_PARAMAMPLIPROFH	27
#define CAMEROA_REP_OK_PARAMAMPLIPROFV		28
#define CAMEROA_REP_NONOK_PARAMAMPLIPROFV	29


static QString ListeRepServeurCamerOA[NB_REP_SERVEUR_CAMEROA]=
{
	"[<?>]",
	"[<CAMEROA-EN-ATTENTE>]",
	"[<CAMEROA-OK-CTEMP>]",
	"[<CAMEROA-NONOK-CTEMP>]",
	"[<CAMEROA-OK-CTPI>]",
	"[<CAMEROA-NONOK-CTPI>]",
	"[<CAMEROA-OK-CTPC>]",
	"[<CAMEROA-NONOK-CTPC>]",
	"[<CAMEROA-OK-POSE-IMAGE>]",
	"[<CAMEROA-OK-STOP-POSE-IMAGE>]",
	"[<CAMEROA-OK-OBTU-OUVERT>]",
	"[<CAMEROA-OK-OBTU-FERME>]",
	"[<CAMEROA-OK-VENT-LOW>]",
	"[<CAMEROA-OK-VENT-MEDIUM>]",
	"[<CAMEROA-OK-VENT-HIGH>]",
	"[<CAMEROA-OK-VENT-OFF>]",
	"[<CAMEROA-TEMP-CCD>]",
	"[<CAMEROA-TEMP-RADIATEUR>]",
	"[<CAMEROA-PUI-PELTIER>]",
	"[<CAMEROA-OK-MODE-POSEC-A-OBTU>]",
	"[<CAMEROA-OK-MODE-POSEC-S-OBTU>]",
	"[<CAMEROA-OK-POSE-IMAGE-DOUBLE>]",
	"[<CAMEROA-OK-POSE-IMAGE-BIAS>]",
	"[<CAMEROA-OK-POSE-IMAGE-DARK>]",
	"[<CAMEROA-OK-CONS-TPD>]",
	"[<CAMEROA-NONOK-CONS-TPD>]",
	"[<CAMEROA-OK-PARAM-AMPLI-PROFIL-H>]",
	"[<CAMEROA-NONOK-PARAM-AMPLI-PROFIL-H>]",
	"[<CAMEROA-OK-PARAM-AMPLI-PROFIL-V>]",
	"[<CAMEROA-NONOK-PARAM-AMPLI-PROFIL-V>]",
	""
};

#endif

